describe("review help", function()
  it("documents the primary workflows and recovery commands", function()
    local lines = require("review.ui.help").lines()
    local text = table.concat(lines, "\n")
    assert.is_truthy(text:find(":ReviewList", 1, true))
    assert.is_truthy(text:find(":ReviewComments", 1, true))
    assert.is_truthy(text:find(":ReviewSync", 1, true))
    assert.is_truthy(text:find("<Tab>", 1, true))
    assert.is_truthy(text:find("<C%-q>"))
  end)
end)
